close all; clear variables;
% This script reads .mat data as output from AnalyzeMean.m for all cases
% analyzed in Li and Fox-Kemper, 2017, JPO, and save the mean profiles
% in a netCDF file.
%
% Prepare data for Langmuir test in CVMix.
% Qing Li, 20180130

% setup cases
caseList = {'R7_BF05WD05WV00_ST00_ens01',...
            'R7_BF05WD05WV01_ST00_ens01',...
            'R7_BF05WD05WV02_ST00_ens01',...
            'R7_BF05WD05WV03_ST00_ens01',...
            'R7_BF05WD05WV04_ST00_ens01',...
            'R7_BF05WD05WV12_ST00_ens01',...
            'R7_BF05WD05WV13_ST00_ens01',...
            'R7_BF05WD05WV14_ST00_ens01',...
            'R7_BF05WD08WV00_ST00_ens01',...
            'R7_BF05WD08WV01_ST00_ens01',...
            'R7_BF05WD08WV02_ST00_ens01',...
            'R7_BF05WD08WV03_ST00_ens01',...
            'R7_BF05WD08WV04_ST00_ens01',...
            'R7_BF05WD08WV12_ST00_ens01',...
            'R7_BF05WD08WV13_ST00_ens01',...
            'R7_BF05WD08WV14_ST00_ens01',...
            'R7_BF05WD10WV00_ST00_ens01',...
            'R7_BF05WD10WV01_ST00_ens01',...
            'R7_BF05WD10WV02_ST00_ens01',...
            'R7_BF05WD10WV03_ST00_ens01',...
            'R7_BF05WD10WV04_ST00_ens01',...
            'R7_BF05WD10WV12_ST00_ens01',...
            'R7_BF05WD10WV13_ST00_ens01',...
            'R7_BF05WD10WV14_ST00_ens01',...
            'R7_BF10WD05WV00_ST00_ens01',...
            'R7_BF10WD05WV01_ST00_ens01',...
            'R7_BF10WD05WV03_ST00_ens01',...
            'R7_BF25WD05WV00_ST00_ens01',...
            'R7_BF25WD05WV01_ST00_ens01',...
            'R7_BF25WD05WV03_ST00_ens01',...
            'R7_BF25WD08WV00_ST00_ens01',...
            'R7_BF25WD08WV01_ST00_ens01',...
            'R7_BF25WD08WV03_ST00_ens01',...
            'R7_BF25WD10WV00_ST00_ens01',...
            'R7_BF25WD10WV01_ST00_ens01',...
            'R7_BF25WD10WV03_ST00_ens01',...
            'R7_BF50WD05WV00_ST00_ens01',...
            'R7_BF50WD05WV01_ST00_ens01',...
            'R7_BF50WD05WV03_ST00_ens01',...
            'R7_BF50WD08WV00_ST00_ens01',...
            'R7_BF50WD08WV01_ST00_ens01',...
            'R7_BF50WD08WV03_ST00_ens01',...
            'R7_BF50WD10WV00_ST00_ens01',...
            'R7_BF50WD10WV01_ST00_ens01',...
            'R7_BF50WD10WV03_ST00_ens01',...
            'R7_BF1hWD05WV00_ST00_ens01',...
            'R7_BF1hWD05WV01_ST00_ens01',...
            'R7_BF1hWD05WV03_ST00_ens01',...
            'R7_BF1hWD08WV00_ST00_ens01',...
            'R7_BF1hWD08WV01_ST00_ens01',...
            'R7_BF1hWD08WV03_ST00_ens01',...
            'R7_BF1hWD10WV00_ST00_ens01',...
            'R7_BF1hWD10WV01_ST00_ens01',...
            'R7_BF1hWD10WV03_ST00_ens01',...
            'R7_BF2hWD05WV00_ST00_ens01',...
            'R7_BF2hWD05WV01_ST00_ens01',...
            'R7_BF2hWD05WV03_ST00_ens01',...
            'R7_BF3hWD05WV00_ST00_ens01',...
            'R7_BF3hWD05WV01_ST00_ens01',...
            'R7_BF3hWD05WV03_ST00_ens01',...
            'R7_BF5hWD05WV00_ST00_ens01',...
            'R7_BF5hWD05WV01_ST00_ens01',...
            'R7_BF5hWD05WV03_ST00_ens01',...
            };

% Input and output variable name and meta data
% constants
var1dListIn = {'h', 'hm', 'hb', 'hb_kpp',...
               'utau', 'u10', 'fcor', 'wtsfc'};
var1dListOut = {'hml', 'hbl', 'hbl_eps', 'hb_kpp',...
               'utau', 'u10', 'fcor', 'bfsfc'};
var1dLongName = {'Mixed layer depth (min(w''b''))',...
                 'Boundary layer depth (max(N2))',...
                 'Boundary layer depth (dissipation)',...
                 'Boundary layer depth (KPP)',...
                 'Water-side friction velocity',...
                 '10-meter wind speed',...
                 'Coriolis parameter',...
                 'Surface buoyancy flux'};
var1dUnits = {'m', 'm', 'm', 'm', 'm/s', 'm/s', '1/s', 'm^2/s^3'};

% profiles at u level
var2dzuListIn = {'bxym', 'uxym', 'vxym', 'uv', 'ups', 'vps',...
                 'tps', 'stokes'};
var2dzuListOut = var2dzuListIn;
var2dzuLongName = {'Mean buoyancy',...
                   'Mean horizontal velocity, x-component',...
                   'Mean horizontal velocity, y-component',...
                   'Reynolds stress (uv)',...
                   'Reynolds stress (uu)',...
                   'Reynolds stress (vv)',...
                   'Temperature variance',...
                   'Stokes drift'};
var2dzuUnits = {'m/s^2', 'm/s', 'm/s', 'm^2/s^2', 'm^2/s^2', 'm^2/s^2',...
                'degC^2', 'm/s'};

% profiles at w level
var2dzwListIn = {'wb', 'uw', 'vw', 'wps', 'N2', 'tke', 'wSkew',...
                 'stokesProd', 'shearProd', 'tkeTrans', 'dissip'};
var2dzwListOut = var2dzwListIn;
var2dzwLongName = {'Vertical buoyancy flux',...
                   'Reynolds stress (uw)',...
                   'Reynolds stress (vw)',...
                   'Reynolds stress (ww)',...
                   'Mean stratification',...
                   'Turbulent kinetic energy',...
                   'Skewness of vertical velocity',...
                   'Stokes production in TKE budget',...
                   'Shear production in TKE budget',...
                   'TKE transport in TKE budget',...
                   'Dissipation in TKE budget'};
var2dzwUnits = {'m^2/s^3', 'm^2/s^2', 'm^2/s^2', 'm^2/s^2', '1/s^2',...
               'm^2/s^2','m^3/s^3', 'm^2/s^3', 'm^2/s^3',...
               'm^2/s^3', 'm^2/s^2'};

ncase = numel(caseList);
nvar1d = numel(var1dListIn);
nvar2d_zu = numel(var2dzuListIn);         
nvar2d_zw = numel(var2dzwListIn);
nnz = 160;

vardata_1d = zeros(ncase, nvar1d);
vardata_zu = zeros(ncase, nnz, nvar2d_zu);
vardata_zw = zeros(ncase, nnz, nvar2d_zw);

% read mat data
indir = '/Users/qingli/GoogleDrive/BrownWork/Articles/A2017_entr-kpp/matlab/AnalyzeSingleCase';
matname = 'MeanProfile.mat';
for k = 1:ncase
    inname = [indir '/' caseList{k} '/' matname];
    dat = load(inname);
    for i = 1:nvar1d
        if strcmp(var1dListIn{i}, 'wtsfc')
            vardata_1d(k,i) = dat.(var1dListIn{i}).*dat.f.g.*dat.f.alpha;
        elseif strcmp(var1dListIn{i}, 'u10')
            % read in 10 meter wind speed from case name
            vardata_1d(k,i) = str2double(caseList{k}(10:11));
        else
            vardata_1d(k,i) = dat.(var1dListIn{i});
        end
    end
    for i = 1:nvar2d_zu
        vardata_zu(k,:,i) = dat.(var2dzuListIn{i})(1,1:nnz);
    end
    for i = 1:nvar2d_zw
        vardata_zw(k,:,i) = dat.(var2dzwListIn{i})(1,1:nnz);
    end
end
date_str = datestr(now,'yyyymmdd');
outname = ['les_profile_data_' date_str '.nc'];

% create netCDF
ncid = netcdf.create(outname,'clobber');
% Define dimensions
caseDimId = netcdf.defDim(ncid, 'case', ncase); % casename
zwDimId = netcdf.defDim(ncid, 'z_w', nnz);
zuDimId = netcdf.defDim(ncid, 'z_u', nnz);
% Define variables
varid_zu  = netcdf.defVar(ncid, 'z_u', 'double', zuDimId);
netcdf.putAtt(ncid, varid_zu, 'long_name', 'Depth at cell center');
netcdf.putAtt(ncid, varid_zu, 'units', 'm');
varid_zw  = netcdf.defVar(ncid, 'z_w', 'double', zwDimId);
netcdf.putAtt(ncid, varid_zw, 'long_name', 'Depth at cell interface');
netcdf.putAtt(ncid, varid_zw, 'units', 'm');
varid_case  = netcdf.defVar(ncid, 'case', 'int', caseDimId);
varid1d = zeros(nvar1d,1);
varid2d_zu = zeros(nvar2d_zu,1);
varid2d_zw = zeros(nvar2d_zw,1);
for i = 1:nvar1d
    varid1d(i) = netcdf.defVar(ncid, var1dListOut{i},...
        'double', caseDimId);
    netcdf.putAtt(ncid, varid1d(i), 'long_name', var1dLongName{i});
    netcdf.putAtt(ncid, varid1d(i), 'units', var1dUnits{i});
end
for i = 1:nvar2d_zu
    varid2d_zu(i) = netcdf.defVar(ncid, var2dzuListOut{i},...
        'double', [zuDimId, caseDimId]);
    netcdf.putAtt(ncid, varid2d_zu(i), 'long_name', var2dzuLongName{i});
    netcdf.putAtt(ncid, varid2d_zu(i), 'units', var2dzuUnits{i});
end
for i = 1:nvar2d_zw
    varid2d_zw(i) = netcdf.defVar(ncid, var2dzwListOut{i},...
        'double', [zwDimId, caseDimId]);
    netcdf.putAtt(ncid, varid2d_zw(i), 'long_name', var2dzwLongName{i});
    netcdf.putAtt(ncid, varid2d_zw(i), 'units', var2dzwUnits{i});
end
% global attributes
casenames = strjoin(caseList);
varid_global = netcdf.getConstant('NC_GLOBAL');
netcdf.putAtt(ncid, varid_global, 'casenames', casenames);
netcdf.putAtt(ncid, varid_global, 'author', 'Qing Li');
netcdf.putAtt(ncid, varid_global, 'date', char(datetime));
description = 'Profile data from LES used in Li and Fox-Kemper, 2017, JPO.';
netcdf.putAtt(ncid, varid_global, 'description', description);

% end define mode
netcdf.endDef(ncid);

% write to netCDF file
netcdf.putVar(ncid, varid_zw, dat.z_w(1:nnz));
netcdf.putVar(ncid, varid_zu, dat.z_u(1:nnz));
netcdf.putVar(ncid, varid_case, 1:ncase);
for i = 1:nvar1d
    vardata = squeeze(vardata_1d(:,i));
    netcdf.putVar(ncid, varid1d(i), vardata);
end
for i = 1:nvar2d_zu
    vardata = squeeze(vardata_zu(:,:,i));
    netcdf.putVar(ncid, varid2d_zu(i), vardata');
end
for i = 1:nvar2d_zw
    vardata = squeeze(vardata_zw(:,:,i));
    netcdf.putVar(ncid, varid2d_zw(i), vardata');
end

% close netCDF file
netcdf.close(ncid)

