tmp = f.getVar('udpdx');
IPS11 = -2.*tmp(1:nnzmax,end);
figure;plot(PS11, '-k'); hold on; plot(IPS11, '--K');
tmp = f.getVar('vdpdy');
IPS22 = -2.*tmp(1:nnzmax,end);
figure;plot(PS22, '-k'); hold on; plot(IPS22, '--K');
tmp = f.getVar('wdpdz');
IPS33 = -2.*tmp(1:nnzmax,end);
figure;plot(PS33, '-k'); hold on; plot(IPS33, '--K');
tmp = f.getVar('udpdy')+f.getVar('vdpdx');
IPS12 = -tmp(1:nnzmax,end);
figure;plot(PS12, '-k'); hold on; plot(IPS12, '--K');
tmp = f.getVar('udpdz')+f.getVar('wdpdx');
IPS13 = -tmp(1:nnzmax,end);
figure;plot(PS13, '-k'); hold on; plot(IPS13, '--K');
tmp = f.getVar('vdpdz')+f.getVar('wdpdy');
IPS23 = -tmp(1:nnzmax,end);
figure;plot(PS23, '-k'); hold on; plot(IPS23, '--K');

tmp = f.getVar('dsle11');
ID11 = -tmp(1:nnzmax,end);
figure;plot(D11, '-k'); hold on; plot(ID11, '--K');
tmp = f.getVar('dsle22');
ID22 = -tmp(1:nnzmax,end);
figure;plot(D22, '-k'); hold on; plot(ID22, '--K');
tmp = f.getVar('dsle33');
ID33 = -tmp(1:nnzmax,end);
figure;plot(D33, '-k'); hold on; plot(ID33, '--K');
tmp = f.getVar('dsle12');
ID12 = -tmp(1:nnzmax,end);
figure;plot(D12, '-k'); hold on; plot(ID12, '--K');
tmp = f.getVar('dsle13');
ID13 = -tmp(1:nnzmax,end);
figure;plot(D13, '-k'); hold on; plot(ID13, '--K');
tmp = f.getVar('dsle23');
ID23 = -tmp(1:nnzmax,end);
figure;plot(D23, '-k'); hold on; plot(ID23, '--K');

tmp = f.getVar('ttau11');
ITV11 = tmp(1:nnzmax,end);
figure;plot(TV11, '-k'); hold on; plot(ITV11, '--K');
tmp = f.getVar('ttau22');
ITV22 = tmp(1:nnzmax,end);
figure;plot(TV22, '-k'); hold on; plot(ITV22, '--K');
tmp = f.getVar('ttau33');
ITV33 = tmp(1:nnzmax,end);
figure;plot(TV33, '-k'); hold on; plot(ITV33, '--K');
tmp = f.getVar('ttau12');
ITV12 = tmp(1:nnzmax,end);
figure;plot(TV12, '-k'); hold on; plot(ITV12, '--K');
tmp = f.getVar('ttau13');
ITV13 = tmp(1:nnzmax,end);
figure;plot(TV13, '-k'); hold on; plot(ITV13, '--K');
tmp = f.getVar('ttau23');
ITV23 = tmp(1:nnzmax,end);
figure;plot(TV23, '-k'); hold on; plot(ITV23, '--K');
